[project]
name = "calcofi-spark-regression"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.7",
    "numpy>=2.3.3",
    "pyspark>=4.0.1",
]
